from __future__ import annotations

FETCH_DEBOUNCE_MS = 600
PROGRESS_ANIM_MS = 33
UI_EVENT_POLL_MS = 25
UI_EVENT_MAX_PER_TICK = 200
FORMAT_CACHE_MAX_ENTRIES = 100
HISTORY_MAX_ENTRIES = 250
WINDOW_MIN_WIDTH = 720
WINDOW_MIN_HEIGHT = 550
WINDOW_SCREEN_MARGIN = 8

VIDEO_CONTAINERS = ("mp4", "webm")
AUDIO_CONTAINERS = ("m4a", "mp3", "opus", "wav", "flac")
