from __future__ import annotations


VIDEO_CONTAINERS = ("mp4", "webm")
AUDIO_CONTAINERS = ("m4a", "mp3", "opus", "wav", "flac")
CODECS = ("avc1", "av01")

FETCH_DEBOUNCE_MS = 600
PANEL_SWITCH_FADE_MS = 260
HISTORY_MAX_ENTRIES = 250
LOG_MAX_LINES = 1000
MIN_WINDOW_WIDTH = 1040
MIN_WINDOW_HEIGHT = 820
DEFAULT_WINDOW_WIDTH = MIN_WINDOW_WIDTH
DEFAULT_WINDOW_HEIGHT = MIN_WINDOW_HEIGHT
ROOMY_CONTENT_LAYOUT_MIN_HEIGHT = 1020
FLOATING_SOURCE_TOAST_MIN_WIDTH = 1180
SOURCE_DETAILS_NONE_INDEX = 0
SOURCE_DETAILS_PLAYLIST_INDEX = 1
TOP_ACTION_ICON_PX = 16
